apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: ollyfad/udagram-api-feed:v3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1024Mi"
            cpu: "400m"
          limits:
            memory: "2048Mi"
            cpu: "700m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: aws-volume
            mountPath: /root/.aws
        envFrom:
          - configMapRef:
              name: udagram-configmap
          - secretRef:
              name: udagram-secret
      restartPolicy: Always
      volumes:
        - name: aws-volume
          secret:
            secretName: aws-secret
            items:
            - key: credentials
              path: credentials