apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: ollyfad/udagram-api-user:v3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1024Mi"
            cpu: "400m"
          limits:
            memory: "2048Mi"
            cpu: "700m"
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: aws-volume
            mountPath: /root/.aws
        envFrom:
          - configMapRef:
              name: udagram-configmap
          - secretRef:
              name: udagram-secret
      restartPolicy: Always
      volumes:
        - name: aws-volume
          secret:
            secretName: aws-secret
            items:
            - key: credentials
              path: credentials