apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
     containers:
      - image: ollyfad/udagram-reverseproxy:v4
        name: reverseproxy
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "1024Mi"
            cpu: "400m"
          limits:
            memory: "2048Mi"
            cpu: "700m"

---
apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  type: ClusterIP
  selector:
    app: reverseproxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-reverseproxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reverseproxy
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70